version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      # TODO relocate to include Ansible dependency in custom image
      - run: sudo apt update && sudo apt install python-setuptools python-dev python-yaml libssl-dev libffi-dev

      - run: sudo easy_install ansible==2.6.0

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "plugins-parent/pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Ensure buildtools (plugin validator) are present
          command: ./mvnw -f plugin-validator/pom.xml clean install -B

      - run:
          name: Ensure buildtools (plugin assembly descriptor) are present
          command: ./mvnw -f plugins-assembly-descriptor/pom.xml clean install -B

      - run:
          name: Ensure project reactor lines up
          command: ./mvnw -f plugins-parent/pom.xml clean -B

      - run:
          name: Build/Test
          command: ./mvnw -f plugins-parent/pom.xml install -B

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "plugins-parent/pom.xml" }}

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp -fv {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/junit
